### ISSUE TITLE
Fix styling issue with some CKAN artifacts

### ISSUE THREAD

**Issue by kentsanggds** [alphagov/ckanext-datagovuk#1871]
For example -  `Add dataset` and `Add publisher`, but `Add Harvest Source` is working as that is managed by this repo

![Screenshot 2024-11-07 at 11 16 02](https://github.com/user-attachments/assets/013afcb6-8afa-4bb7-a69a-0dac6e7d1820)

![Screenshot 2024-11-07 at 11 15 56](https://github.com/user-attachments/assets/31db3dc4-be68-4652-94e0-0465f8a86ca0)

![Screenshot 2024-11-07 at 11 15 48](https://github.com/user-attachments/assets/6cdc6396-851c-4fd6-8426-f3980f4d83d5)

An upgrade of CKAN to 2.11 might fix this, otherwise the website is running as expected.

**Comment by kentsanggds** [comment]
https://github.com/alphagov/ckanext-datagovuk/pull/1884

**Comment by nicholsj** [comment]
Fixed by https://github.com/alphagov/ckanext-datagovuk/pull/1884
